### ISSUE TITLE
Slowness on pico + ILI9341 (2.8" spi)

### ISSUE THREAD

**Issue by alxtr1bal** [tuupola/hagl_pico_mipi#10]
Hello !! 

I'm trying to run the old school demo on the pico with ILI9341. Question is : is this supposed to be slow on this kind of screen ?
I'm not able to achieved a lot of fps , i think for plasma it's 14 fps max , and then it hangs on the second effect .. 

(i had to comment the busy_wait_until (start + US_PER_FRAME_60_FPS); to achieve some fps !) 
By the way, busy_wait_until waits for an absolute_time_t type, so it's not compiling anyway (update ?)

I tried using triple buffering, but it can't link as there not enough space on the pico( i guess ?) (error : firmware.elf section `.bss' will not fit in region `RAM')

Am i doing something wrong ?

thanks;

**Comment by tuupola** [comment]
This  belongs to [tuupola/pico_effects](https://github.com/tuupola/pico_effects) but I will answer here. 

> I'm not able to achieved a lot of fps , i think for plasma it's 14 fps max , and then it hangs on the second effect ..

You do not mention the resolution of the display but I assume the usual 320x240. I remember from testing the driver can update 320x240 screen approximately 30 fps. Actual speed mostly depends on the SPI clock speed. However bigger the screen the longer it takes to render the effect so you will not be achieving 30fps demo effects with a 320x240 display.

Also it most likely hangs because there is not enough memory to run the effects on bigger screen. For testing you can configure your screen in the `CMakeLists.txt` to be smaller than actual size, for example 160x120.

> By the way, busy_wait_until waits for an absolute_time_t type, so it's not compiling anyway (update ?)

Do not enable debug build ie. do not use `CMAKE_BUILD_TYPE=Debug`. Pico SDK uses different datatypes depending on the build type.

> I tried using triple buffering, but it can't link as there not enough space on the pico( i guess ?) (error : firmware.elf section .bss' will not fit in region RAM')

You are correct there is not enough memory for the buffers. You could configure the demo to use smaller resolutions for testing purposes.

**Comment by alxtr1bal** [comment]
Hi, thanks for the explanations ... 
> This belongs to tuupola/pico_effects but I will answer here.

You are correct, i posted on the wrong repository.

> but I assume the usual 320x240.

You are correct again :)

I'll try lowering the screen size and see what that does for the demo !

Anyway, many thanks for this great library.
